[versions]
#Android Gradle Plugin. Без него Android Studio не сможет собрать проект.
agp = "8.11.2"
#Kotlin. Это версия компилятора Kotlin.
kotlin = "2.0.21"
#AndroidX Core KTX. Основа Android KTX. Содержит расширения Kotlin (KTX) для базовых фреймворков Android.
coreKtx = "1.17.0"
#JUnit 4. Юнит-тестирование (базовое).
junit = "4.13.2"
#AndroidX JUnit. Инструментальное тестирование (Instrumentation Tests).
junitVersion = "1.3.0"
#Espresso. UI-тестирование.
espressoCore = "3.7.0"
#Корутины для LifeCycle(активити или фрагмент)
lifecycleRuntimeKtx = "2.8.0"
#Activity KTX для Compose. Интеграция Compose с Activity.
activityCompose = "1.11.0"
#Compose Bill of Materials (BOM). Управление версиями Compose. BOM гарантирует, что все модули Jetpack Compose (например, material, ui, foundation) используют совместимые версии.
composeBom = "2025.08.00"

#просмотр изображений.
coil = "2.6.0"
#ViewModel и Coroutines (корутины для ViewModel)
viewmodelKtx = "2.8.0"
#Навигация Compose
navigationCompose = "2.9.4"

[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
androidx-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
androidx-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
androidx-ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }
androidx-material3 = { group = "androidx.compose.material3", name = "material3" }

#просмотр изображений.
coil-compose = { group = "io.coil-kt", name = "coil-compose", version.ref = "coil"}
# Добавь ViewModel
androidx-lifecycle-viewmodel-ktx = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "viewmodelKtx" }
# Добавь Navigation
androidx-navigation-compose = { module = "androidx.navigation:navigation-compose", version.ref = "navigationCompose" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }

